begin;

-- Persist the four score layers at the exact lifecycle transition where they
-- were observed. The legacy recorder only copied confidence/risk/volume.
create or replace function public.record_signal_journey_event()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  event_id uuid;
  horizon smallint;
  candle_interval interval;
begin
  if tg_op = 'UPDATE'
    and old.status is not distinct from new.status
    and old.journey_id is not distinct from new.journey_id then
    return new;
  end if;

  insert into public.signal_journey_events(
    analysis_model_id, journey_id, breakout_signal_id, symbol_id, timeframe,
    status, candle_close_time, price, breakout_level, confidence,
    false_breakout_risk, volume_ratio,
    regime_score, readiness_score, breakout_quality_score,
    confirmation_score, breakout_triggered, scoring_version
  ) values (
    new.analysis_model_id, new.journey_id, new.id, new.symbol_id, new.timeframe,
    new.status, new.candle_close_time, new.signal_price, new.breakout_level,
    new.breakout_confidence_score, new.false_breakout_risk, new.volume_ratio,
    new.regime_score, new.readiness_score, new.breakout_quality_score,
    new.confirmation_score, new.breakout_triggered, new.scoring_version
  )
  on conflict (breakout_signal_id, journey_id, status, candle_close_time) do nothing
  returning id into event_id;

  if event_id is not null and new.status = 'breakout_detected' then
    candle_interval := case new.timeframe
      when '15m' then interval '15 minutes'
      when '30m' then interval '30 minutes'
      when '1h' then interval '1 hour'
      when '2h' then interval '2 hours'
      when '4h' then interval '4 hours'
      when '6h' then interval '6 hours'
      when '1d' then interval '1 day'
      else interval '15 minutes'
    end;

    foreach horizon in array array[1, 4, 12]::smallint[] loop
      insert into public.signal_outcome_snapshots(
        analysis_model_id, journey_id, breakout_signal_id, origin_event_id,
        symbol_id, timeframe, horizon_candles, entry_price, entry_close_time,
        breakout_level, due_at
      ) values (
        new.analysis_model_id, new.journey_id, new.id, event_id,
        new.symbol_id, new.timeframe, horizon, new.signal_price,
        new.candle_close_time, new.breakout_level,
        new.candle_close_time + candle_interval * horizon
      )
      on conflict (journey_id, horizon_candles) do nothing;
    end loop;
  end if;
  return new;
end;
$$;

-- The event generated by the deployment smoke test predates the corrected
-- recorder. Only copy values when event and signal still describe the exact
-- same candle and phase, avoiding look-ahead contamination of older events.
update public.signal_journey_events event
   set regime_score = signal.regime_score,
       readiness_score = signal.readiness_score,
       breakout_quality_score = signal.breakout_quality_score,
       confirmation_score = signal.confirmation_score,
       breakout_triggered = signal.breakout_triggered,
       scoring_version = signal.scoring_version
  from public.breakout_signals signal
 where event.breakout_signal_id = signal.id
   and event.candle_close_time = signal.candle_close_time
   and event.status = signal.status
   and event.regime_score is null;

update public.journey_state state
   set regime_score = signal.regime_score,
       readiness_score = signal.readiness_score,
       breakout_quality_score = signal.breakout_quality_score,
       confirmation_score = signal.confirmation_score,
       breakout_triggered = signal.breakout_triggered,
       scoring_version = signal.scoring_version,
       updated_at = now()
  from public.breakout_signals signal
 where state.symbol_id = signal.symbol_id
   and state.analysis_model_id = signal.analysis_model_id
   and state.timeframe = signal.timeframe
   and state.candle_close_time = signal.candle_close_time;

-- Keep notification filtering and copy aligned with the new primary quality
-- score while retaining the legacy confidence field as a safe fallback.
create or replace function public.enqueue_matching_signal_notifications()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  matched record;
  notification_id uuid;
  dedup_key text;
  status_title text;
  notification_body text;
  quality_score integer;
begin
  quality_score := coalesce(new.breakout_quality_score, new.breakout_confidence_score, 0);

  for matched in
    select p.id as user_id, p.preferred_language, s.symbol
    from public.profiles p
    join public.symbols s on s.id = new.symbol_id
    where p.notifications_enabled
      and p.preferred_analysis_model_id = new.analysis_model_id
      and exists (
        select 1 from public.subscription_entitlements e
        where e.user_id = p.id
          and e.status in ('active', 'grace_period')
          and e.expires_at > now()
      )
      and p.preferred_timeframe = new.timeframe
      and quality_score >= p.minimum_breakout_score
      and new.false_breakout_risk <= p.maximum_false_breakout_risk
      and coalesce(new.volume_ratio, 0) >= p.minimum_volume_ratio
      and new.status = any(p.notification_statuses)
      and (
        p.notification_scope = 'all'
        or exists (
          select 1
          from public.watchlists w
          join public.watchlist_items wi on wi.watchlist_id = w.id
          where w.user_id = p.id and wi.symbol_id = new.symbol_id
        )
      )
  loop
    status_title := case
      when matched.preferred_language = 'tr' then case new.status
        when 'pre_breakout' then 'Kırılım Bekleniyor'
        when 'breakout_detected' then 'Kırılım Başladı'
        when 'confirmed' then 'Kırılım Güçleniyor'
        when 'retest' then 'Seviye Test Ediliyor'
        when 'failed' then 'Sinyal Geçersiz Oldu'
        when 'expired' then 'Takip Tamamlandı'
        else new.status end
      else case new.status
        when 'pre_breakout' then 'Waiting for Breakout'
        when 'breakout_detected' then 'Breakout Started'
        when 'confirmed' then 'Breakout Strengthening'
        when 'retest' then 'Level Being Tested'
        when 'failed' then 'Signal Invalidated'
        when 'expired' then 'Tracking Complete'
        else new.status end
    end;

    notification_body := case when matched.preferred_language = 'tr'
      then 'Kırılım kalitesi ' || quality_score || '/100 · Risk %' || new.false_breakout_risk || ' · Hacim ' || round(coalesce(new.volume_ratio, 0), 1) || 'x'
      else 'Breakout quality ' || quality_score || '/100 · Risk ' || new.false_breakout_risk || '% · Volume ' || round(coalesce(new.volume_ratio, 0), 1) || 'x'
    end;

    dedup_key := matched.user_id::text || ':' || new.id::text || ':' || new.candle_close_time::text || ':' || new.status;
    insert into public.notifications(
      user_id, breakout_signal_id, title, body, notification_type,
      deduplication_key, signal_status
    ) values (
      matched.user_id, new.id, matched.symbol || ' · ' || status_title,
      notification_body, 'breakout_signal', dedup_key, new.status
    )
    on conflict (deduplication_key) where deduplication_key is not null do nothing
    returning id into notification_id;

    if notification_id is not null then
      insert into public.notification_queue(notification_id, deduplication_key)
      values (notification_id, dedup_key)
      on conflict (deduplication_key) do nothing;
    end if;
    notification_id := null;
  end loop;
  return new;
end;
$$;

commit;
